import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import NavbarContainer from "@/components/NavbarContainer";
import { Toaster } from "@/components/ui/toaster";
import { Provider } from "@radix-ui/react-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      ><Provider>
        <NavbarContainer>
          <Navbar />
        </NavbarContainer>
        {children}
        <Toaster />
      </Provider>
      </body>
    </html>
  );
}
